language: go
go:
  - 1.13.x
script:
  - make travis
deploy:
  provider: releases
  api_key:
    secure: cnW0us8VBEztRQVHblityiZVHD1axdaZHZLt3mwhkYF9lkUOjXlq8shqAQDqDR7DrRy3kOpkccVS0nrxGJvlGYp9rrlcQdYySB45OO7rKV+AgKcFDiLBxPuyjfOb72dlyGq6S116bMjaa8XkPZ/HmNNKxDmGXJhghAes/9kT3M3N0eSdWJpGZlsyX99oFIoHAuwGqeYVoKi6sVnA0uGX2Gb/erYpJkfRdotUNjGPqGwE1otLKsUi21XtX6L8v7kO7VqPYELsrYArTvVkJIT6MKnOrJi1kCbF5WeczbsUs6ArjVR+6b4JVscpwzSxSnUvxszHd3ZVbQCec5FagmLnJ2k2EsyL+23tqBeppoqQW7aXGNcJMnWBj8tNYMflIRelrW/eKbVohnyBc5gAL5ui3huEYaaNag5pVGI+ceFvIoXbgmt2GJ3u1fE2GnrCQlL0QTHmGFBQTghnggzypKIpeQdRtTkSIqTDB54AEOC/pgHghvysHsb0+3N6NQedhMp0Hvv1lobDmsh7UqZdbZlESmiF44CsTJOaynN4gAjiAbpmbvQ//SNicY5N6BhQp6gPmU3DuLAFuEaW3x59rU5t5gg7FYqjm3VmOs7XP5tXuEXS5Ji3pLVr6GthYm1yFqb8//xSsvcwDude3+ucAFHoWXbXDqZyGFnyil/RTsH4hg0=
  file_glob: true
  file: target/*
  skip_cleanup: true
  on:
    tags: true
